---
title: "Research"
---

------------------------------------------------------------------------

"$\dagger$" indicates equal contribution; "$*$" indicates student author.

### Submitted Papers

1.  **Zeng, J.**, Min, K. and Mai, Q. Robust Sliced Inverse Regression: Optimal Estimation for Heavy-Tailed Data in High Dimensions.

2.  **Zeng, J.**, Zhang, X. and Hao, N. Second-Order Sparse Suﬃcient Dimension Reduction with Applications to Quadratic Discriminant Analysis.

4.  Liu, H.$^*$ and **Zeng, J.** Regularized Sufficient Dimension Reduction for Multivariate Response via Distance Covariance.

5. Wang, N. and **Zeng, J.** High-Dimensional Best Subset Selection Based EM Algorithm for Mixed Linear Regression Model.

### Publications

#### *Papers*

1.  Huang, W.$^*$, Mai, Q. and **Zeng, J.** (2026) Sparse Robust Discriminant Analysis for High-Dimensional and Heavy-Tailed Data. *Biometrics*, just-accepted.

1.  **Zeng, J.**$^\dagger$, Wang, N.$^\dagger$ and Zhang, X. (2025) Envelope Inverse Regression for Dimension Reduction: A Review and New Perspectives. *Journal of Systems Science and Complexity*, accepted.

2.  Chen, L.$^\dagger$ and **Zeng, J.**$^\dagger$ (2024+). Dimension Reduction for Extreme Regression via Contour Projection. *Statistics Sinica*, just-accepted. [\[pdf\]](papers/COPES.pdf)

3.  **Zeng, J.**, Mai, Q. and Zhang, X. (2024). Subspace Estimation with Automatic Dimension and Variable Selection in Sufficient Dimension Reduction. *Journal of the American Statistical Association*, 119(545), 343--355. [\[pdf\]](papers/SEAS.pdf)

4.  Li, L.$^\dagger$, **Zeng, J.**$^\dagger$ and Zhang, X.$^\dagger$ (2023). Generalized Liquid Association Analysis for Multimodal Data Integration. *Journal of the American Statistical Association*, 118(543), 1984--1996. [\[pdf\]](papers/GLAA.pdf)

5.  **Zeng, J.**, Zhang, X. and Mai, Q. (2023). An Efficient Convex Formulation for Reduced-Rank Linear Discriminant Analysis in High Dimensions. *Statistics Sinica*, 33, 1249-1270. [\[pdf\]](papers/LSLDA.pdf)

6.  **Zeng, J.**, Wang, W. and Zhang, X. (2021). TRES: An R Package for Tensor Regression and Envelope Algorithms. *Journal of Statistical Software*, 99, 1-31. [\[pdf\]](papers/TRES.pdf)[\[R package\]](https://github.com/leozeng15/TRES)

#### *Book Chapters*

1.  **Zeng, J.** and Zhang, X. (2024). Tensor and Multimodal Data Analysis. In: Gaw, N., Pardalos, P.M., Gahrooei, M.R. (eds) *Multimodal and Tensor Data Analytics for Industrial Systems Improvement*. Springer Optimization and Its Applications, vol 211. Springer, Cham.

### Acknowledgement

My research is partially supported by the National Natural Science Foundation of China (NSFC) Grant 12301365 (2024.01--2026.12).
